### ISSUE TITLE
Prepare detailed specification on how flaky test detection will work

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#41]
Review relevant information presented in shared word file.

Prepare a detailed plan on how Flaky test detection will work, what components will be used.

Current high-level understanding (can be changed after investigation):
1. Parse JUnit XML
2. For each test - get the previous test run results from Firebase
3. Analyze history & detect Flaky test (specify how the algorithm will work)
4. Display results/Save to Firebase

**Comment by bootstraponline** [comment]
There are two flows:

## 1) Post merge
Flaky test job runs tests 3 times on the master branch in parallel and produces a JUnit XML.

Guardian should:
* Parse JUnit XML
* Upload per test metadata to Firebase

## 2) Pre merge
A feature pull request is submitted and tests run once from the feature branch.

Guardian should:
* Parse JUnit XML
* For each test - get the previous test run results from Firebase
* Analyze history & detect Flaky test
  * A flaky test is a test that in the last 3 runs, did not produce the same result.
* Do *NOT* save results to firebase. The only results we save are from the post merge run. This is because pre-merge test results are expected to be flaky. Post-merge, the tests should be stable.

**Comment by illia-romanenko** [comment]
Thanks @bootstraponline !

For now should we focus on the first flow only? As we are not integrating with test runner yet and we are operating with XMLs only?

Also, I wanted to clarify for the second flow (Pre merge):
>> For each test - get the previous test run results from Firebase
>> A flaky test is a test that in the last 3 runs, did not produce the same result.
>> Do NOT save results to firebase.

so those previous runs are from the master branch?

**Comment by bootstraponline** [comment]
> For now should we focus on the first flow only? As we are not integrating with test runner yet and we are operating with XMLs only?

Correct. Let's solve the first problem of sending the per test data in the JUnit XML to firebase. Once that's solved, we'd move onto the second flow.

> so those previous runs are from the master branch?

Correct. The master branch runs are the source of truth for determining test flakiness.
