### ISSUE TITLE
Skia deployment - enable auto renderer

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#773]
**Description**
For skia site deployment, please enable auto renderer.

**Acceptance Criteria**
- [ ] auto renderer enabled
- [ ] on mobile browser HTML version is dislpayed
- [ ] on desktop browser Skia version is dislpayed

**Additional context**
https://github.com/flutter/engine/pull/21852

**Comment by solid-yuriiuvarov** [comment]
We performed an additional investigation and figured out some blockers for this ticket.
The main trick is to rework the [isSkia](https://github.com/platform-platform/monorepo/blob/a81178a680eab197cbab5e5e4a7854409284ab0f/metrics/web/lib/util/web_platform.dart#L8) method of the [WebPlatform](https://github.com/platform-platform/monorepo/blob/a81178a680eab197cbab5e5e4a7854409284ab0f/metrics/web/lib/util/web_platform.dart#L3) class. This reworking requires the [universal_io](https://pub.dev/packages/universal_io) package to be used as the standard [dart:io](https://api.dart.dev/stable/2.10.2/dart-io/dart-io-library.html) doesn't implement the `Platform.isAndroid` and `Platform.isIOS methods`. However, the latest version of the `universal_io` has an [issue](https://github.com/dint-dev/universal_io/issues/8) in validating iOS systems. Reducing the package version is impossible as well since we're using the [universal_html](https://pub.dev/packages/universal_html) package depending on the latest `universal_io`.
Thus, because of the packages' issues and dependency limitations we have, we cannot complete this ticket at the moment.

**Comment by bootstraponline** [comment]
Can we fix the issue in universal_io to unblock this ticket? I’m not sure is upstream is going to fix this anytime soon.

**Comment by illia-romanenko** [comment]
@bootstraponline we'll take a look further, thanks!
